# Generated by Django 2.1.4 on 2019-06-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skey', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classno', models.CharField(choices=[('1-8', '1-8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('engg', 'engg'), ('ca', 'ca'), ('bsc', 'bsc')], default='12', max_length=15)),
                ('subcode', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skey', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('classno', models.ForeignKey(default='12', on_delete=django.db.models.deletion.CASCADE, to='first_app.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subcode', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('subname', models.CharField(max_length=50)),
                ('classno', models.ForeignKey(default='12', on_delete=django.db.models.deletion.CASCADE, to='first_app.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skey', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('classno', models.ForeignKey(default='12', on_delete=django.db.models.deletion.CASCADE, to='first_app.Classes')),
                ('subcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='subcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Subject'),
        ),
        migrations.AddField(
            model_name='books',
            name='classno',
            field=models.ForeignKey(default='12', on_delete=django.db.models.deletion.CASCADE, to='first_app.Classes'),
        ),
        migrations.AddField(
            model_name='books',
            name='subcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Subject'),
        ),
    ]
