# Generated by Django 2.1.4 on 2019-06-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classno',
            field=models.CharField(choices=[('1-8', '1-8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('engg', 'engg'), ('ca', 'ca'), ('bsc', 'bsc'), ('humanities', 'humanities')], default='12', max_length=15),
        ),
    ]
