# Generated by Django 2.1.4 on 2019-07-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20190627_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='classno',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='classno',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='classno',
        ),
        migrations.AlterField(
            model_name='subject',
            name='classno',
            field=models.CharField(choices=[('1-8', '1-8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('engg', 'engg'), ('ca', 'ca'), ('bsc', 'bsc')], default='12', max_length=15),
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
