# Generated by Django 2.1.4 on 2019-09-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20190702_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='classno',
            field=models.CharField(choices=[('1-8', '1-8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Engineering', 'Engineering'), ('CA', 'CA'), ('B.Sc', 'B.sc')], default='12', max_length=15),
        ),
    ]
